#include <iostream>
using namespace std;
#define MAX 5

struct Stack { // Stack structure to hold Points and the top index
    int num[MAX];
    int top;
};

void create(struct Stack *S) {
    S->top = -1;
}

int isFull(struct Stack *S) {
    return S->top == MAX - 1; 
}

int isEmpty(struct Stack *S) {
    return S->top == -1;
}

void push(struct Stack *S, int x) {
    if (!isFull(S)) {
        (S->top)++;
        S->num[S->top] = x; 
    }

    else
        printf("Stack Overflow\n");
}

int pop(struct Stack *S) {
    if (!isEmpty(S)) {
        int temp = S->num[S->top];
        S->top--;
        return temp;
    }

    else {
        printf("Stack Underflow\n");
        return -1; 
    }
}

int top(struct Stack *S) {
    if (!isEmpty(S)) {
        return S->num[S->top]; 
    }

    else {
        return -1; 
    }
}

int nextToTop(struct Stack *S) {
    if (S->top >= 1) {
        return S->num[S->top - 1];
    }
    
    else {
        return -1; 
    }
}

// Functions below are generated by chatGPT

// Function to display the contents of the stack
void display(struct Stack* s) {
    if (isEmpty(s)) {
        printf("Stack is empty!\n");
        return;
    }
    printf("Stack elements: ");
    for (int i = 0; i <= s->top; i++) {
        printf("%d ", s->num[i]);
    }
    printf("\n");
}

int main() {
    struct Stack s;
    create(&s);

    // Push elements onto the stack
    push(&s, 10);
    push(&s, 20);
    push(&s, 30);
    push(&s, 40);
    push(&s, 50);
    push(&s, 60);  // This should show "Stack Overflow"

    // Display the stack
    display(&s);

    // Pop elements from the stack
    pop(&s);
    pop(&s);

    // Display the stack after popping
    display(&s);

    // Peek at the top element
    printf("Top element is: %d\n", top(&s));
    return 0;
}